<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "v_cuahang".
 *
 * @property integer $id_cuahang
 * @property string $ten_donvi
 * @property string $ten_cuahang
 * @property string $so_nha
 * @property string $ten_duong
 * @property string $ten_phuong
 * @property string $so_sap
 * @property string $ten_cho
 * @property string $dien_tich
 * @property string $nam_hoatdong
 * @property string $nganh_kd
 * @property string $ma_nganh
 * @property integer $loaicuahang_id
 * @property string $tinh_trang
 * @property string $ten_loai
 * @property string $geom
 * @property double $geo_x
 * @property double $geo_y
 */
class VCuahang extends \yii\db\ActiveRecord {

    /**
     * @inheritdoc
     */
    public static function tableName() {
        return 'v_cuahang';
    }

    /**
     * @inheritdoc
     */
    public function rules() {
        return [
            [['id_cuahang', 'loaicuahang_id'], 'integer'],
            [['dien_tich', 'geo_x', 'geo_y'], 'number'],
            [['geom'], 'string'],
            [['ten_donvi', 'ten_cuahang'], 'string', 'max' => 300],
            [['so_nha', 'ten_duong', 'ten_phuong', 'so_sap', 'ten_cho', 'nam_hoatdong', 'nganh_kd', 'ma_nganh','tinh_trang'], 'string', 'max' => 100],
            [['ten_loai'], 'string', 'max' => 200],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels() {
        return [
            'id_cuahang' => 'Id Cuahang',
            'ten_donvi' => 'Tên đơn vị',
            'ten_cuahang' => 'Tên cửa hàng',
            'so_nha' => 'Số nhà',
            'ten_duong' => 'Tên đường',
            'ten_phuong' => 'Tên phường',
            'so_sap' => 'Số sạp',
            'ten_cho' => 'Tên chợ',
            'dien_tich' => 'Diện tích',
            'nam_hoatdong' => 'Năm hoạt động',
            'nganh_kd' => 'Ngành KD',
            'ma_nganh' => 'Mã ngành',
            'ghi_chu' => 'Ghi chú',
            'ten_loai' => 'Loại cửa hàng',
             'tinh_trang' => 'Tình trạng hoạt động',
            'geom' => 'Geom',
            'geo_x' => 'Geo X',
            'geo_y' => 'Geo Y',
        ];
    }

    public static function primaryKey() {
        return ['id_cuahang']; // TODO: Change the autogenerated stub
    }

}
